# Generated by Django 4.1.2 on 2022-12-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_management', '0002_usercarddata_subscriptionlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transaction_token',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
