# Generated by Django 4.1.2 on 2022-12-24 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments_management', '0003_transactions_transaction_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=250, null=True)),
                ('paid_amount', models.CharField(max_length=250, null=True)),
                ('status', models.CharField(choices=[('pending', 'Payment Pending'), ('paid', 'Payment Paid'), ('cancelled', 'Payment Cancelled'), ('hold', 'Payment Hold')], default='initiated', max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(max_length=250, null=True)),
                ('transaction_token', models.CharField(max_length=250, null=True)),
                ('currency', models.CharField(default='AED', max_length=150, null=True)),
            ],
        ),
    ]
