# Generated by Django 4.1.2 on 2022-12-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_management', '0004_paymenttransation'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippack',
            name='expire_days',
            field=models.IntegerField(default=30, null=True),
        ),
    ]
