# Generated by Django 4.1.2 on 2022-12-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_management', '0005_membershippack_expire_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransation',
            name='paid_mode',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
