# Generated by Django 4.1.2 on 2022-11-13 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=50, null=True)),
                ('upload', models.FileField(upload_to='file_manager')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=250, null=True)),
                ('paid_amount', models.CharField(max_length=250, null=True)),
                ('request_type', models.CharField(max_length=150, null=True)),
                ('discription', models.TextField(null=True)),
                ('status', models.CharField(choices=[('approve', 'Approve'), ('decline', 'Decline'), ('initiated', 'Initiated'), ('hold', 'Hold')], max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('documents', models.JSONField(blank=True, default=dict)),
                ('approval_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_user', to=settings.AUTH_USER_MODEL)),
                ('request_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=250, null=True)),
                ('paid_amount', models.CharField(max_length=250, null=True)),
                ('discription', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('documents', models.JSONField(blank=True, default=dict)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
