# Generated by Django 4.1.2 on 2022-11-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesrequests',
            name='transaction_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='servicesrequests',
            name='status',
            field=models.CharField(choices=[('approve', 'Approve'), ('decline', 'Decline'), ('initiated', 'Initiated'), ('hold', 'Hold')], default='initiated', max_length=250, null=True),
        ),
    ]
