# Generated by Django 4.1.2 on 2022-12-02 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0004_managerservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesrequests',
            name='manager_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_user', to='company_app.managerservices'),
        ),
    ]
