# Generated by Django 4.1.2 on 2022-12-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0005_servicesrequests_manager_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemanager',
            name='folder_name',
            field=models.CharField(default='default', max_length=250, null=True),
        ),
    ]
