# Generated by Django 4.1.2 on 2022-12-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0006_filemanager_folder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemanager',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filemanager',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
