# Generated by Django 3.2 on 2023-01-26 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0008_filemanager_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemanager',
            name='expiry_date',
        ),
    ]
