# Generated by Django 4.1.2 on 2022-10-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtuser_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthkey',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
