# Generated by Django 4.1.2 on 2022-10-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtuser_auth', '0002_userauthkey_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauthkey',
            old_name='date',
            new_name='date_time',
        ),
    ]
