# Generated by Django 4.1.2 on 2022-11-04 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0003_managercompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='managercompany',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
