# Generated by Django 4.1.2 on 2022-11-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0004_managercompany_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='documents',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='managercompany',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
