# Generated by Django 4.1.2 on 2022-11-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0005_loginuser_documents_managercompany_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='username',
        ),
    ]
