# Generated by Django 4.1.2 on 2022-11-20 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0006_remove_loginuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('code', models.CharField(default='', max_length=255)),
                ('f_name', models.CharField(default='', max_length=255)),
                ('l_name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
