# Generated by Django 4.1.2 on 2022-11-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0007_employeedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='documents',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
