# Generated by Django 3.2 on 2023-01-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0010_alter_loginuser_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='is_staff',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
