# Generated by Django 3.2 on 2023-01-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0011_auto_20230110_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='is_staff',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
