# Generated by Django 3.2 on 2023-01-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0012_auto_20230110_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='picture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
