# Generated by Django 3.2 on 2023-02-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0013_loginuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
