# Generated by Django 3.2 on 2023-02-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0014_alter_loginuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
