# Generated by Django 3.2 on 2023-03-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0015_loginuser_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='picture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
